---
version: "3"
services:
  db:
    image: postgres:alpine
    environment:
      POSTGRES_DB: "queue"
      POSTGRES_PASSWORD: "secret"
    ports:
      - 5434:5432
    volumes:
      - ./data/db:/var/lib/postgresql/data